# Generated by Django 3.1.5 on 2021-02-09 05:55

from django.db import migrations, models
import django.db.models.deletion
from dbview.helpers import CreateView


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        CreateView(
            name='RelatedPost',
            fields=[
                ('relatedpost_id', models.IntegerField(db_column='relatedpost_id', primary_key=True, serialize=False)),
                ('related_title', models.TextField()),
                ('related_slug', models.TextField()),
                ('related_tags', models.TextField()),
                ('related_count', models.IntegerField(db_column='related_count')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_posts', to='blog.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
