# Generated by Django 3.1.5 on 2021-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_relatedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('url', models.TextField(verbose_name='Url')),
            ],
        ),
    ]
