# Generated by Django 3.1.5 on 2021-02-21 04:21

from django.db import migrations


def insert_links(apps, schema_editor):
    AutoLink = apps.get_model('blog', 'AutoLink')
    AutoLink.objects.bulk_create([
        AutoLink(name='ruby', url='http://www.ruby-lang.org/en/'),
        AutoLink(name='blosxom', url='http://www.blosxom.com/'),
        AutoLink(name='nvidia', url='http://www.nvidia.com/'),
        AutoLink(name='amd', url='http://en.wikipedia.org/wiki/Advanced_Micro_Devices'),
        AutoLink(name='linux', url='http://en.wikipedia.org/wiki/Linux'),
        AutoLink(name='windows', url='http://en.wikipedia.org/wiki/History_of_Microsoft_Windows'),
        AutoLink(name='boinc', url='http://boinc.berkeley.edu/'),
        AutoLink(name='cs', url='http://en.wikipedia.org/wiki/Computer_science'),
        AutoLink(name='xen', url='http://www.xen.org'),
        AutoLink(name='lenny', url='http://www.debian.org/releases/lenny/'),
        AutoLink(name='jessie', url='http://www.debian.org/releases/jessie/'),
        AutoLink(name='squeeze', url='http://www.debian.org/releases/squeeze/'),
        AutoLink(name='wheezy', url='http://www.debian.org/releases/wheezy/'),
        AutoLink(name='stretch', url='http://www.debian.org/releases/stretch/'),
        AutoLink(name='buster', url='http://www.debian.org/releases/buster/'),
        AutoLink(name='bullseye', url='https://www.debian.org/releases/bullseye/'),
        AutoLink(name='PHP', url='http://en.wikipedia.org/wiki/PHP'),
        AutoLink(name='jira', url='http://www.atlassian.com/software/jira/'),
        AutoLink(name='vuejs', url='https://vuejs.org/'),
        AutoLink(name='vue', url='https://vuejs.org/'),
        AutoLink(name='perl', url='https://en.wikipedia.org/wiki/Perl'),
        AutoLink(name='kvm', url='https://www.linux-kvm.org'),
        AutoLink(name='django', url='https://djangoproject.com'),
        AutoLink(name='python', url='https://www.python.org/')
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_autolink'),
    ]

    operations = [
        migrations.RunPython(insert_links),
    ]
